---
title: "BDS522 - Final Project"
---

##The Impact of Income, Parents Education and Type of School on Academic Performance

#### Case study on the Brazilian city of Belo Horizonte

In 1996, famous sociologist James Samuel Coleman published "Equality of Educational Opportunity", most commonly known as the "Coleman Report", an extensive and thorough 700 pages study about the quality of education in the U.S. His work was one of the first to show the power of the relationship between family background and a success in school. As Coleman explained in 1972, "all factors considered, the most important variable-in or out of school-in a child's performance remains his family's education background."

Importance of family background as a predictor of scholar performance has been a solid empirical finding till this day, and many sociological studies have explored this association. The two most commonly studied variables as a predictor of a child's performance are the parents' level of education and the family income. How these family traits affect school performance, however, is not so clear. One hypothesis is that parents with higher education value the study of their children more and are in a better position to support and tutor them than less educated parents. Also, it is believed that parents with higher income will be willing to spend more to make sure their children attend the best schools, as well as invest in out-of-school activities. On the other hand, economically disadvantaged families do not have access to the same schools and resources which can stimulate the development of various skills that can help in school performance.
 
The debate over the power of family background and the potential limitations of the "school effect" are the main motivators for our analysis. Our main goal is to understand if this commonly identified empirical effect is observed in the particular case of Brazil. Specifically, we will analyze ENEM's scores of Brazilian high school students from the city of Belo Horizonte and if they can be predicted by the students' family income, parents' educational level and the type of school they attend. 
 
Similar to the SAT, the Brazilian High School National Exam (ENEM) score is used by most universities as the sole criteria to admit new students. The two-day exam happens once a year at the same time across the country and over 4,6 million of students took the exam in 2017. We will use data provided by the Brazilian Ministry of Education of the 2017 ENEM to test our hypothesis that family background and the type of high school predicts the average scored achieved in the exam. More specifically, we believe that higher averages of family income and education level of parents will result in higher average ENEM scores. Also, we believe that Private schools will also perform better in the exam on average than Public schools. 

